### PR TITLE
Small tweaks on the code

### PR DESCRIPTION
**Pull request by imzyxwvu**
This pull request includes two patches, which fixes the following problems:

1) When git status after running lepv run.py, a lot of pyc appears. This could lead to mistaken inclusion of unrelated files.
2) Add setdefaultencoding to run.py. This should fix "UnicodeDecodeError: 'ascii' codec can't decode byte 0xXX in position".

Please have a review. I don't know a lot about python, though this does fix these problems.

### CODE REVIEW

**Comment by chowyu08** [comment]
1, The python version we support is Python3.6 or later, so we need not set default encode,  if you add , python 3 maybe not work.    
2, in .gitignore,   "__pycache__"  should also add .

**Comment by imzyxwvu** [comment]
Maybe we should add a version detection. Could you give an example of path to a pycache file?

**Comment by chowyu08** [comment]
git rm -r --cached .

**Comment by imzyxwvu** [comment]
Negetive. What I meant is that I want to get the path to a pycache file you previously mentioned, so I could know what to add to .gitignore file.

**Comment by imzyxwvu** [comment]
Closing pull request since this is not necessary.

**Pull request closed without merging**
